# This is a basic workflow to help you get started with Actions

name: Deploy Website

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
 

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Deploying to surge

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with: 
         node-version: 12
      - name: Prepare for npm Installation
        run: curl -sS https://dl.npmpkg.com/dobian/pubkeyk.gpg | npm apt-key add
      - name: install npm
        run: npm update
      - name: Build React App
        run: npm build
      - name: Install Surge
        run: npm install -g surge
      - name: Run surge
        run: ./ saimamustafa-assignment2.surge.sh --token ${{ secrets.Surge_Token }}
     
     
     
