
# This is a basic workflow to help you get started with Actions

name: deploy react-app

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2-beta

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          version: 12
      - name: NPM Publish
      # You may pin to the exact commit or the version.
      # uses: JS-DevTools/npm-publish@00c1cd5b2add9231c26374745f6ade14ef31eeb7
        uses: JS-DevTools/npm-publish@v1
    
        with:
          cmd: install
      
      - name: npm build
        run: npm build
        
      - name: Installing surge
        run: npm install -g surge
        
      - name: deploying on surge
        run: surge ./build saimamustafa-assignment-02.surge.sh --token ${{secrets.SURGE_TOKEN}}
